# Generated by Django 2.0 on 2018-01-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group',
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_permission',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('column_a', models.CharField(blank=True, db_column='column_A', max_length=500, null=True)),
                ('column_b', models.CharField(blank=True, db_column='column_B', max_length=500, null=True)),
                ('option_right1', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'comparison',
            },
        ),
        migrations.CreateModel(
            name='Comprehension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.TextField()),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('option_4', models.CharField(blank=True, max_length=100, null=True)),
                ('option_5', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'comprehension',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_admin_log',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_session',
            },
        ),
        migrations.CreateModel(
            name='FillBlanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(blank=True, max_length=20, null=True)),
                ('option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right1', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'fill_Blanks',
            },
        ),
        migrations.CreateModel(
            name='MultipleMath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('option_4', models.CharField(blank=True, max_length=100, null=True)),
                ('option_5', models.CharField(blank=True, max_length=100, null=True)),
                ('option_6', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right3', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'multiple_math',
            },
        ),
        migrations.CreateModel(
            name='NumericEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('option_right_int', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right_frac', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'numeric_entry',
            },
        ),
        migrations.CreateModel(
            name='SentenceEquivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('difficulty_level', models.CharField(max_length=20)),
                ('option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('option_4', models.CharField(blank=True, max_length=100, null=True)),
                ('option_5', models.CharField(blank=True, max_length=100, null=True)),
                ('option_6', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right1', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right2', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right3', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right4', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right5', models.CharField(blank=True, max_length=100, null=True)),
                ('option_right6', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sentence_equivalence',
            },
        ),
    ]
